spring.application.name=STOCK

spring.datasource.url=jdbc:mysql://localhost:3306/newstock?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Tokyo&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

server.port=8080

spring.messages.basename=messages
spring.messages.encoding=UTF-8

stock.validation.enabled=false
stock.validation.url=

app.twelvedata.base-url=https://api.twelvedata.com
app.twelvedata.api-key=a832240414544c8cb3d97861207ce83a

app.fmp.base-url=https://financialmodelingprep.com
app.fmp.api-key=XTJSzWK7IPixX1iRjk7E5uFtGDo6Kyag